### ISSUE TITLE
error running app : The activity 'MainActivity' is not declared in AndroidManifest.xml

### ISSUE THREAD

**Issue by voltumna** [CAAPIM/Sample-App-MAS-Android-Login-User-Authentication-And-Authorization#13]
Hi, I cannot seem to compile and run the application:
I have android studio, 
I imported the project, 
created the app and put the json in
and when I try to run it it complains that there is no MainActivity

thanks

**Comment by voltumna** [comment]
OK, forget about it, I had to restart android studio, apparently it is a known bug: 
https://stackoverflow.com/questions/40183700/the-activity-mainactivity-is-not-declared-in-androidmanifest-xml/55628668

**Comment by arindamhit** [comment]
@voltumna as you mentioned that issue is not there, we are closing this ticket.
